export declare const DataIds: {
    readonly search: "search";
    readonly navigation: "navigation";
    readonly sidebar: "sidebar-menu";
    readonly menuCode: "menu-code";
    readonly menuRelations: "menu-relations";
    readonly menuDocs: "menu-docs";
    readonly menuExport: "menu-export";
    readonly menuImport: "menu-import";
    readonly menuDiff: "menu-diff";
    readonly diffView: "diff-view";
    readonly codeView: "code-view";
    readonly docsView: "docs-view";
    readonly relationView: "relation-view";
    readonly graphNode: "graph-node";
    readonly nodeFocus: "node-focus";
    readonly nodeEditExpand: "node-edit-expand";
    readonly defocus: "defocus";
    readonly newNode: "newNode";
    readonly filter: "filter";
    readonly relationsOnly: "relations-only";
    readonly libraryNodes: "library-nodes";
    readonly export: "export";
    readonly zoom: "zoom";
    readonly activeNode: "active-node";
    readonly nodeDescription: "node-description";
    readonly addField: "add-field";
    readonly implementInterface: "implement-interface";
    readonly addDirective: "add-directive";
    readonly nodeOptions: "node-options";
    readonly nodeField: "node-field";
    readonly fieldName: "field-name";
    readonly fieldType: "field-type";
    readonly fieldList: "field-list";
    readonly fieldExpand: "field-expand";
    readonly fieldArgs: "field-args";
    readonly fieldOptions: "field-options";
};
export declare const dataIt: (d: keyof typeof DataIds) => {
    "data-id": "search" | "navigation" | "sidebar-menu" | "menu-code" | "menu-relations" | "menu-docs" | "menu-export" | "menu-import" | "menu-diff" | "diff-view" | "code-view" | "docs-view" | "relation-view" | "graph-node" | "node-focus" | "node-edit-expand" | "defocus" | "newNode" | "filter" | "relations-only" | "library-nodes" | "export" | "zoom" | "active-node" | "node-description" | "add-field" | "implement-interface" | "add-directive" | "node-options" | "node-field" | "field-name" | "field-type" | "field-list" | "field-expand" | "field-args" | "field-options";
};
