"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PRINT_PREVIEW_RELATION_NODE_MAX_WIDTH = exports.PRINT_PREVIEW_RELATION_NODE_MAX_FIELDS = exports.RELATION_NODE_MAX_WIDTH = exports.RELATION_NODE_MAX_FIELDS = void 0;
exports.RELATION_NODE_MAX_FIELDS = 15;
exports.RELATION_NODE_MAX_WIDTH = 800;
exports.PRINT_PREVIEW_RELATION_NODE_MAX_FIELDS = 150;
exports.PRINT_PREVIEW_RELATION_NODE_MAX_WIDTH = 1200;
